service: maverick-analytics-api

provider:
        name: aws
        stage: dev
        region: ap-northeast-2

plugins:
        - serverless-offline

functions:
        node-function-example:
                runtime: nodejs12.x
                handler: handlers/nodejs-example.workName
                events:
                        - http:
                                method: get
                                path: nodejs/work-name
        py-function-example:
                runtime: python3.7
                handler: handlers/py-example.handlerName
                events:
                        - http:
                                method: post
                                path: py-example/test
